#!/usr/bin/with-contenv bash
echo "Starting NetDaemon Runner"

declare daemondir="/daemon"
declare is_custom_app_source=false

if [ ! -d "/data" ]; then
    echo -e "\\033[31mMissing mapping to apps, please map '/data' to your apps folder\\033[0m" >&2
    exit 1
fi

if [ ! -f "/data/options.json" ]; then
    echo -e "\\033[31mThis container only supports running as Home Assistant add-on!\\033[0m" >&2
    exit 1
fi

# Get the settings for application source
export NETDAEMON__APPLICATION_ASSEMBLY=$( jq -r .app_assembly /data/options.json )

if [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" == *.csproj ]]; 
then
    echo -e "\\033[31mcsproj deployments are not supported in v3, use compiled option instead!\\033[0m" >&2
    exit 1
fi

if [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" == *.csproj ]]; 
then
    echo -e "\\033[31mcsproj deployments are not supported in v3, use compiled option instead!\\033[0m" >&2
    exit 1
fi

if [[ ! -z "${NETDAEMON__APPLICATION_ASSEMBLY}" ]] && [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" != *".dll" ]];
then
    echo -e "\\033[31mAssembly needs to point to a .dll file!\\033[0m" >&2
    exit 1
fi

if [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" == *.dll ]]; 
then 
    is_custom_app_source=true

    # make path relative to data folder (/config/netdaemon if addon) 
    # if the path is a relative path
    if [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" != /* ]];
    then
        export NETDAEMON__APPLICATION_ASSEMBLY="/config/netdaemon3/${NETDAEMON__APPLICATION_ASSEMBLY}"
    fi 

    # The provided application source is ether a project or pre-compiled .Net application
    if [ ! -f ${NETDAEMON__APPLICATION_ASSEMBLY} ];
    then
        
        echo -e "\\033[31mThe assembly ${NETDAEMON__APPLICATION_ASSEMBLY} cannot be found. Please check the settings.\\033[0m" >&2
        exit 1
    fi
fi

if  [[ $is_custom_app_source == false ]]; then
    echo -e "\\033[32mRunning NetDaemon at ${daemondir}...\\033[0m" >&2
    cd "${daemondir}"
    exec dotnet NetDaemon.Host.AddOn.dll
else 
    # This is a pre-built deamon
    echo -e "\\033[32mRunning the pre-built NetDaemon at ${NETDAEMON__APPLICATION_ASSEMBLY}...\\033[0m" >&2
    cd "$(dirname "${NETDAEMON__APPLICATION_ASSEMBLY}")" || echo -e "\\033[31mCould not change directory to run project\\033[0m" >&2

    if [[ "${PWD}" != "$(dirname "${NETDAEMON__APPLICATION_ASSEMBLY}")" ]]; then
        echo -e "\\033[31mCould not change directory to run custom project\\033[0m" >&2
        exit 1
    fi
    runme="$(basename "${NETDAEMON__APPLICATION_ASSEMBLY}")" 
    exec dotnet $runme
fi

