# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 90

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 7

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Label to use when marking as stale
staleLabel: stale

markComment: >
  There hasn't been any activity on this issue recently. Due to the high number
  of incoming GitHub notifications, we have to clean some of the old issues,
  as many of them have already been resolved with the latest updates.
  Please make sure to update to the latest Home Assistant version and check
  if that solves the issue. Let us know if that works for you by adding a
  comment ðŸ‘
  This issue now has been marked as stale and will be closed if no further
  activity occurs. Thank you for your contributions.

# Handle pull requests a little bit faster and with an adjusted comment.
pulls:
    daysUntilStale: 30
    markComment: >
      There hasn't been any activity on this pull request recently. This pull
      request has been automatically marked as stale because of that and will
      be closed if no further activity occurs within 7 days.
      Thank you for your contributions.
