codecov:
  require_ci_to_pass: yes

coverage:
  precision: 0
  round: down
  range: "70...100"
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 70%  # we always want 70% coverage here
    patch:
      default:
        # basic
        target: auto
        threshold: 10%
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
