namespace NetDaemon.HassModel.Entities;

// These 'Core' interfaces serve as common types between 3rd party libraries and classes that are generated by the end
// user using nd-codegen  

/// <summary>Common interface for switch entities</summary>
public interface ISwitchEntityCore: IEntityCore { }

/// <summary>Common interface for light entities</summary>
public interface ILightEntityCore: IEntityCore { }

/// <summary>Common interface for binary_sensor entities</summary>
public interface IBinarySensorEntityCore: IEntityCore { }