namespace NetDaemon.HassModel.Entities;

// These 'Core' interfaces serve as common types between 3rd party libraries and classes that are generated by the end
// user using nd-codegen  

/// <summary> Core interface for automation entities </summary>
public interface IAutomationEntityCore: IEntityCore {}

/// <summary> Core interface for binary_sensor entities </summary>
public interface IBinarySensorEntityCore: IEntityCore {}

/// <summary> Core interface for button entities </summary>
public interface IButtonEntityCore: IEntityCore {}

/// <summary> Core interface for calendar entities </summary>
public interface ICalendarEntityCore: IEntityCore {}

/// <summary> Core interface for camera entities </summary>
public interface ICameraEntityCore: IEntityCore {}

/// <summary> Core interface for climate entities </summary>
public interface IClimateEntityCore: IEntityCore {}

/// <summary> Core interface for cover entities </summary>
public interface ICoverEntityCore: IEntityCore {}

/// <summary> Core interface for device_tracker entities </summary>
public interface IDeviceTrackerEntityCore: IEntityCore {}

/// <summary> Core interface for group entities </summary>
public interface IGroupEntityCore: IEntityCore {}

/// <summary> Core interface for input_boolean entities </summary>
public interface IInputBooleanEntityCore: IEntityCore {}

/// <summary> Core interface for input_button entities </summary>
public interface IInputButtonEntityCore: IEntityCore {}

/// <summary> Core interface for input_datetime entities </summary>
public interface IInputDatetimeEntityCore: IEntityCore {}

/// <summary> Core interface for input_number entities </summary>
public interface IInputNumberEntityCore: IEntityCore {}

/// <summary> Core interface for input_select entities </summary>
public interface IInputSelectEntityCore: IEntityCore {}

/// <summary> Core interface for input_text entities </summary>
public interface IInputTextEntityCore: IEntityCore {}

/// <summary> Core interface for light entities </summary>
public interface ILightEntityCore: IEntityCore {}

/// <summary> Core interface for lock entities </summary>
public interface ILockEntityCore: IEntityCore {}

/// <summary> Core interface for media_player entities </summary>
public interface IMediaPlayerEntityCore: IEntityCore {}

/// <summary> Core interface for number entities </summary>
public interface INumberEntityCore: IEntityCore {}

/// <summary> Core interface for person entities </summary>
public interface IPersonEntityCore: IEntityCore {}

/// <summary> Core interface for proximity entities </summary>
public interface IProximityEntityCore: IEntityCore {}

/// <summary> Core interface for remote entities </summary>
public interface IRemoteEntityCore: IEntityCore {}

/// <summary> Core interface for scene entities </summary>
public interface ISceneEntityCore: IEntityCore {}

/// <summary> Core interface for schedule entities </summary>
public interface IScheduleEntityCore: IEntityCore {}

/// <summary> Core interface for script entities </summary>
public interface IScriptEntityCore: IEntityCore {}

/// <summary> Core interface for select entities </summary>
public interface ISelectEntityCore: IEntityCore {}

/// <summary> Core interface for sensor entities </summary>
public interface ISensorEntityCore: IEntityCore {}

/// <summary> Core interface for sun entities </summary>
public interface ISunEntityCore: IEntityCore {}

/// <summary> Core interface for switch entities </summary>
public interface ISwitchEntityCore: IEntityCore {}

/// <summary> Core interface for timer entities </summary>
public interface ITimerEntityCore: IEntityCore {}

/// <summary> Core interface for update entities </summary>
public interface IUpdateEntityCore: IEntityCore {}

/// <summary> Core interface for vacuum entities </summary>
public interface IVacuumEntityCore: IEntityCore {}

/// <summary> Core interface for weather entities </summary>
public interface IWeatherEntityCore: IEntityCore {}

/// <summary> Core interface for zone entities </summary>
public interface IZoneEntityCore: IEntityCore {}


