namespace NetDaemon.HassModel.Entities;

// These 'Core' interfaces serve as common types between 3rd party libraries and classes that are generated by the end
// user using nd-codegen  

/// <summary>Common interface for switch entities</summary>
public interface ISwitchEntityCore: IEntityCore { }

/// <summary>Common interface for light entities</summary>
public interface ILightEntityCore: IEntityCore { }

/// <summary>Common interface for binary_sensor entities</summary>
public interface IBinarySensorEntityCore: IEntityCore { }

/// <summary> Common interface for person entities </summary>
public interface IPersonEntityCore: IEntityCore { }

/// <summary> Common interface for zone entities </summary>
public interface IZoneEntityCore: IEntityCore { }

/// <summary> Common interface for sun entities </summary>
public interface ISunEntityCore: IEntityCore { }

/// <summary> Common interface for input_button entities </summary>
public interface IInputButtonEntityCore: IEntityCore { }

/// <summary> Common interface for sensor entities </summary>
public interface ISensorEntityCore: IEntityCore { }

/// <summary> Common interface for weather entities </summary>
public interface IWeatherEntityCore: IEntityCore { }

/// <summary> Common interface for device_tracker entities </summary>
public interface IDeviceTrackerEntityCore: IEntityCore { }

/// <summary> Common interface for media_player entities </summary>
public interface IMediaPlayerEntityCore: IEntityCore { }

/// <summary> Common interface for button entities </summary>
public interface IButtonEntityCore: IEntityCore { }

/// <summary> Common interface for camera entities </summary>
public interface INumberEntityCore: IEntityCore { }

/// <summary> Common interface for select entities </summary>
public interface ISelectEntityCore: IEntityCore { }

/// <summary> Common interface for automation entities </summary>
public interface IAutomationEntityCore: IEntityCore { }