AppModelApps.MyConfig:
  SomeInt: 123456789
  WhoCooks: input_select.who_cooks
  Notifications:
    -
      Title: Notification 1
      Message: Hello from Appmodel
    -
      Title: Notification 2
      Message: Another cheer from Appmodel
